language: python
# command to install dependencies
install: "pip install tox"
# command to run tests
script:
  - export TOX_ENV=py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_DRF}
  - tox -r -e "$TOX_ENV"
matrix:
  include:
    - python: "3.8"
      env: DJANGO_DRF="django32-drf312"
    - python: "3.8"
      env: DJANGO_DRF="django32-drf313"
    - python: "3.8"
      env: DJANGO_DRF="django32-drf314"
    - python: "3.9"
      env: DJANGO_DRF="django32-drf312"
    - python: "3.9"
      env: DJANGO_DRF="django32-drf313"
    - python: "3.9"
      env: DJANGO_DRF="django32-drf314"
    - python: "3.9"
      env: DJANGO_DRF="django40-drf312"
    - python: "3.9"
      env: DJANGO_DRF="django40-drf313"
    - python: "3.9"
      env: DJANGO_DRF="django40-drf314"
    - python: "3.9"
      env: DJANGO_DRF="django41-drf312"
    - python: "3.9"
      env: DJANGO_DRF="django41-drf313"
    - python: "3.9"
      env: DJANGO_DRF="django41-drf314"
    - python: "3.10"
      env: DJANGO_DRF="django40-drf312"
    - python: "3.10"
      env: DJANGO_DRF="django40-drf313"
    - python: "3.10"
      env: DJANGO_DRF="django40-drf314"
    - python: "3.10"
      env: DJANGO_DRF="django41-drf312"
    - python: "3.10"
      env: DJANGO_DRF="django41-drf313"
    - python: "3.10"
      env: DJANGO_DRF="django41-drf314"
    - python: "3.10"
      env: DJANGO_DRF="django41-drfmaster"
    - python: "3.10"
      env: DJANGO_DRF="djangomaster-drf314"
    - python: "3.10"
      env: DJANGO_DRF="djangomaster-drfmaster"
  allow_failures:
    - python: "3.10"
      env: DJANGO_DRF="django41-drfmaster"
    - python: "3.10"
      env: DJANGO_DRF="djangomaster-drf314"
    - python: "3.10"
      env: DJANGO_DRF="djangomaster-drfmaster"

